const proAlias = {
    treeSelect: "TreeSelect",
    city: "City",
    grid: "Grid",
    gridItem: "GridItem",
};

const alias = {
    button: "Button",
    icon: "Icon",
    slider: "Slider",
    rate: "Rate",
    upload: "fcUpload",
    cascader: "Cascader",
    colorPicker: "ColorPicker",
    timePicker: "TimePicker",
    datePicker: "DatePicker",
    switch: "iSwitch",
    select: "fcSelect",
    checkbox: "fcCheckbox",
    radio: "fcRadio",
    inputNumber: "InputNumber",
    input: "Input",
    formItem: "FormItem",
    form: "Form",
    // frame: "fcFrame",
    row: "Row",
    col: "Col",
    tabs: "Tabs",
    tabPane: "TabPane",
    collapse: "Collapse",
    panel: "Panel",
    tree: "fcTree",
    autoComplete: "AutoComplete",
    group: "fcGroup",
    subForm: "fcSubForm",
    object: "fcSubForm",
    divider: "Divider",
};
export default {
    ...alias,
    ...proAlias,
};
