export default {
    button: "Button",
    icon: "Icon",
    slider: "Slider",
    rate: "Rate",
    upload: "fcUpload",
    cascader: "Cascader",
    colorPicker: "ColorPicker",
    timePicker: "TimePicker",
    datePicker: "DatePicker",
    switch: "iSwitch",
    select: "fcSelect",
    checkbox: "fcCheckbox",
    radio: "fcRadio",
    inputNumber: "InputNumber",
    input: "Input",
    formItem: "FormItem",
    form: "Form",
    frame: "fcFrame",
    col: "Col",
    row: "Row",
    tree: "fcTree",
    autoComplete: "AutoComplete",
    group: "fcGroup",
    subForm: "fcSubForm",
    object: "fcSubForm",
    divider: "Divider",
};
